# Generated by Django 5.1.6 on 2025-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('medicines', models.ManyToManyField(related_name='prescriptions', to='medicines.medicine')),
            ],
        ),
    ]
